{
 "title": "Custom exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Server State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Useage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "{{core}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "disk usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_usage_percent", "legendFormat": "{{disk}}" }
   ]
  },
  {
   "title": "Network received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "network_bytes_received", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "network sent bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "network_bytes_sent", "legendFormat": "__auto" }
   ]
  },
  { "title": "Mysql DB State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "queries counts",
   "type": "timeseries",
   "description": "현재 실행된 쿼리 수",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "mysql_queries", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "innodb buffer pool read requests",
   "type": "timeseries",
   "description": "버퍼 풀에서 읽기 요청 수",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "mysql_innodb_buffer_pool_read_requests",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mysql connected",
   "type": "timeseries",
   "description": "현재 연결 클라이언트 수",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "mysql_threads_connected", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "slow queries",
   "type": "timeseries",
   "description": "처리 시간이 긴 쿼리의 수 (10초 이상)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    { "expr": "mysql_slow_queries", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}