{
 "title": "DUMC_Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Target Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Health Check",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oci_instanceaccessibilitystatus{job=\"Bastion_CloudCompute_Exporter_info_Metrics\", instance=\"193.123.237.96:9999\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Target CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",job=\"Bastion_Node_Exporter_Info_Metrics\"}[5m]))) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target NAS Disk Useage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  (1 - (node_filesystem_free_bytes{job=\"Bastion_Node_Exporter_Info_Metrics\",mountpoint=\"/pacs_backup/Nasbk\"} / node_filesystem_size_bytes{job=\"Bastion_Node_Exporter_Info_Metrics\", mountpoint=\"/pacs_backup/Nasbk\"})) * 100, \r\n  \"mountpoint\", \r\n  \"$1\", \r\n  \"mountpoint\", \r\n  \"/pacs_backup/Nasbk/(.*)\"\r\n)\r\n",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Target RAM  Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"Bastion_Node_Exporter_Info_Metrics\"} / node_memory_MemTotal_bytes{job=\"Bastion_Node_Exporter_Info_Metrics\"})) * 100",
     "legendFormat": "Real"
    }
   ]
  },
  {
   "title": "Network Traffic (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"10.175_Target_node_exporter_info\",device=~\"(?i)^(ens|eth).+$\"}[5m])  > 0",
     "legendFormat": "IN ({{device}})"
    },
    {
     "expr": "- irate(node_network_transmit_bytes_total{job=\"10.175_Target_node_exporter_info\",device=~\"(?i)^(ens|eth).+$\"}[5m]) < 0",
     "legendFormat": "OUT ({{device}})"
    }
   ]
  },
  {
   "title": "Disk I/O (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(rate(node_disk_read_bytes_total{device=\"sdb\",job=\"10.175_Target_node_exporter_info\"}[5m]), \"device\", \"Nasbk\", \"device\", \"sdb\")\r\n",
     "legendFormat": "{{device}} Read "
    },
    {
     "expr": "label_replace(rate(node_disk_written_bytes_total{device=\"sdb\", job=\"10.175_Target_node_exporter_info\"}[5m]), \"device\", \"Nasbk\", \"device\", \"sdb\")\r\n\r\n",
     "legendFormat": "{{device}} Write"
    }
   ]
  },
  { "title": "OCI Object Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Buckit File Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oci_objectcount{job=\"10.174_oci_buckit_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buckit Store bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oci_storedbytes{job=\"10.174_oci_buckit_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buckit File Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 20 },
   "targets": [
    {
     "expr": "oci_objectcount{job=\"10.174_oci_buckit_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "OCI IPSec VPN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Tunnel status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "oci_tunnelstate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 32 },
   "targets": [
    { "expr": "oci_vpn", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tunnel Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 32 },
   "targets": [
    { "expr": "oci_vpn", "legendFormat": "__auto" }
   ]
  }
 ]
}