{
 "title": "OCI Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "OCI Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Health Check",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oci_instanceaccessibilitystatus",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  { "title": "OCI VCN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "VCN Received Traffic bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "oci_vnicfromnetworkbytes", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "VCN sent Traffic bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "oci_vnictonetworkbytes", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "VCN Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "oci_vnicfromnetworkpackets", "legendFormat": "{{resource_id}}" }
   ]
  },
  {
   "title": "VCN Sent Packet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "oci_vnictonetworkpackets", "legendFormat": "{{resource_id}}" }
   ]
  },
  { "title": "OCI Object Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Buckit Store bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oci_storedbytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Buckit File Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oci_objectcount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Buckit Store Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "oci_storedbytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Buckit File Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    { "expr": "oci_objectcount", "legendFormat": "__auto" }
   ]
  },
  { "title": "OCI IPsec VPN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Tunnel status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oci_tunnelstate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tunnel status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "targets": [
    { "expr": "oci_tunnelstate", "legendFormat": "__auto" }
   ]
  }
 ]
}