{
 "title": "DUMC_Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "DUMC OCI Bastion Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Health Check",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oci_instanceaccessibilitystatus{customer=\"dumc\",job=\"OCI_Bastion_CloudCompute_Custom_Exporter_info_Metrics\",instance=\"193.123.237.96:9999\",resource_name=\"duk_pub_bastion_svr\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "NAS CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",job=\"Bastion_Node_Exporter_Info_Metrics\",customer=\"dumc\"}[1m]))) * 100",
     "legendFormat": "Real"
    }
   ]
  },
  {
   "title": "NAS Disk Useage (%)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  (1 - (node_filesystem_free_bytes{job=\"Bastion_Node_Exporter_Info_Metrics\", mountpoint=\"/pacs_backup/Nasbk\",customer=\"dumc\"} / node_filesystem_size_bytes{job=\"Bastion_Node_Exporter_Info_Metrics\",mountpoint=\"/pacs_backup/Nasbk\",customer=\"dumc\"})) * 100, \r\n  \"mountpoint\", \r\n  \"$1\", \r\n  \"mountpoint\", \r\n  \"/pacs_backup/Nasbk/(.*)\"\r\n)\r\n",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "NAS RAM  Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"Bastion_Node_Exporter_Info_Metrics\"} / node_memory_MemTotal_bytes{job=\"Bastion_Node_Exporter_Info_Metrics\",customer=\"dumc\"})) * 100",
     "legendFormat": "Real"
    }
   ]
  },
  {
   "title": "NAS Disk Useage (Bytes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{customer=\"dumc\",job=\"Bastion_Node_Exporter_Info_Metrics\",mountpoint=\"/pacs_backup/Nasbk\",device=\"/dev/sdf2\"} - node_filesystem_free_bytes{customer=\"dumc\",job=\"Bastion_Node_Exporter_Info_Metrics\",mountpoint=\"/pacs_backup/Nasbk\",device=\"/dev/sdf2\"}",
     "legendFormat": "Used  |                   "
    },
    {
     "expr": "node_filesystem_size_bytes{customer=\"dumc\",job=\"Bastion_Node_Exporter_Info_Metrics\",mountpoint=\"/pacs_backup/Nasbk\",device=\"/dev/sdf2\"}",
     "legendFormat": "Total  | "
    }
   ]
  },
  {
   "title": "Network Traffic (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"Bastion_Node_Exporter_Info_Metrics\",device=~\"(?i)^(ens|eth).+$\",customer=\"dumc\"}[5m])  > 0",
     "legendFormat": "IN ({{device}})"
    },
    {
     "expr": "- irate(node_network_transmit_bytes_total{job=\"Bastion_Node_Exporter_Info_Metrics\",device=~\"(?i)^(ens|eth).+$\",customer=\"dumc\"}[5m]) < 0",
     "legendFormat": "OUT ({{device}})"
    }
   ]
  },
  {
   "title": "Disk I/O (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(rate(node_disk_read_bytes_total{device=\"sdf\",job=\"Bastion_Node_Exporter_Info_Metrics\",customer=\"dumc\"}[5m]), \"device\", \"Nasbk\", \"device\", \"sdf\")",
     "legendFormat": "{{device}} Read "
    },
    {
     "expr": "label_replace(rate(node_disk_written_bytes_total{device=\"sdf\",job=\"Bastion_Node_Exporter_Info_Metrics\",customer=\"dumc\"}[5m]), \"device\", \"Nasbk\", \"device\", \"sdf\")\r\n",
     "legendFormat": "{{device}} Write"
    }
   ]
  },
  { "title": "OCI Object Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Buckit File Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oci_objectcount{job=\"OCI_Bastion_CloudBuckit_Custom_Exporter_info_Metrics\",customer=\"dumc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buckit Store bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oci_storedbytes{job=\"OCI_Bastion_CloudBuckit_Custom_Exporter_info_Metrics\",customer=\"dumc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buckit File Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oci_objectcount{job=\"OCI_Bastion_CloudBuckit_Custom_Exporter_info_Metrics\",customer=\"dumc\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  { "title": "OCI IPSec VPN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Tunnel status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "oci_tunnelstate{customer=\"dumc\",job=\"OCI_Bastion_CloudIPSecVPN_Custom_Exporter_info_Metrics\",resource_name=\"Tunnel-1\"}",
     "legendFormat": "{{resource_name}}"
    },
    {
     "expr": "oci_tunnelstate{customer=\"dumc\",job=\"OCI_Bastion_CloudIPSecVPN_Custom_Exporter_info_Metrics\",resource_name=\"Tunnel-2\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Error Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "oci_packetserror{job=\"OCI_Bastion_CloudIPSecVPN_Custom_Exporter_info_Metrics\",customer=\"dumc\",}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Tunnel Traffic (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "oci_bytesreceived{job=\"OCI_Bastion_CloudIPSecVPN_Custom_Exporter_info_Metrics\",customer=\"dumc\",resource_name=\"Tunnel-1\"}",
     "legendFormat": "{{resource_name}} Received"
    },
    {
     "expr": "oci_bytessent{job=\"OCI_Bastion_CloudIPSecVPN_Custom_Exporter_info_Metrics\",customer=\"dumc\",resource_name=\"Tunnel-1\"}",
     "legendFormat": "{{resource_name}} Sent"
    },
    {
     "expr": "oci_bytesreceived{job=\"OCI_Bastion_CloudIPSecVPN_Custom_Exporter_info_Metrics\",customer=\"dumc\",resource_name=\"Tunnel-2\"}",
     "legendFormat": "{{resource_name}} Received"
    },
    {
     "expr": "oci_bytessent{job=\"OCI_Bastion_CloudIPSecVPN_Custom_Exporter_info_Metrics\",customer=\"dumc\",resource_name=\"Tunnel-2\"}",
     "legendFormat": "{{resource_name}} Sent"
    }
   ]
  }
 ]
}