{
 "title": "Monitoring_Tem",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"position: relative; height: 50px; width: 100%; overflow: hidden; background: rgb(247, 247, 247); border: 1px solid rgb(214, 214, 214); border-radius: 10px;\">\r\n    <!-- 중간 파란 박스 추가 -->\r\n    <div style=\"position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 10; width: 13px; height: 48px; background: rgb(159, 186, 255);\"></div>\r\n    \r\n    <!-- 원들이 지나가는 영역 -->\r\n    <div style=\"position: absolute; top: 50%; transform: translateY(-50%); display: flex; gap: 10px;\">\r\n        <div class=\"dot\" style=\"animation: move 2.0s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.3s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.6s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.8s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.6s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.1s linear infinite; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.3s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.8s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.6s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.1s linear infinite; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.7s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.1s linear infinite 0.2s; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.8s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.6s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.8s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.6s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.1s linear infinite; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.1s linear infinite; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.8s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.6s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.1s linear infinite; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.8s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.3s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.8s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.6s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.1s linear infinite; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 1.1s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.3s linear infinite 0.2s; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.8s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.6s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.1s linear infinite; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.8s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.4s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.8s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.6s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.1s linear infinite; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.0s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 1.3s linear infinite 0.2s; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.4s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.9s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.5s linear infinite 0.2s; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.8s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.6s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.1s linear infinite; background: rgb(255, 185, 163); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 2.7s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.1s linear infinite 0.2s; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n        <div class=\"dot\" style=\"animation: move 3.0s linear infinite; background: rgb(191, 210, 255); width: 8px; height: 8px; border-radius: 50%;\"></div>\r\n    </div>\r\n</div>\r\n\r\n<style>\r\n@keyframes move {\r\n    0% { transform: translateX(-50%); }\r\n    100% { transform: translateX(120vw); } /* 뷰포트 기준 이동 */\r\n}\r\n</style>\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 2 },
   "options": {
    "content": "<img src=\"https://pds.saramin.co.kr/company/logo/202211/23/rlsdr6_d56p-1mo99bb_logo.png\" alt=\"info\" />\r\n"
   }
  },
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"10.178_mariadb_master_node_exporter_info\"} - node_boot_time_seconds{job=\"10.178_mariadb_master_node_exporter_info\"}"
    }
   ]
  },
  {
   "title": "Core",
   "type": "stat",
   "description": "Number of processors",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"10.178_mariadb_master_node_exporter_info\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "description": "Amount of memory",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"10.178_mariadb_master_node_exporter_info\"}"
    }
   ]
  },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\", job=\"10.178_mariadb_master_node_exporter_info\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"10.178_mariadb_master_node_exporter_info\"} - node_memory_MemAvailable_bytes{job=\"10.178_mariadb_master_node_exporter_info\"}) / sum(node_memory_MemTotal_bytes{job=\"10.178_mariadb_master_node_exporter_info\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\", job=\"10.178_mariadb_master_node_exporter_info\"}[5m])",
     "legendFormat": "{{device}}_read I/O"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{device=\"sda\", job=\"10.178_mariadb_master_node_exporter_info\"}[5m])",
     "legendFormat": "{{device}}_writre I/O"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"10.178_mariadb_master_node_exporter_info\",fstype!~\"(tmpfs|rootfs)\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic | $host",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"10.178_mariadb_master_node_exporter_info\",device=~\"(?i)^(ens|eth).+$\"}[5m])  > 0",
     "legendFormat": "IN ({{device}})"
    },
    {
     "expr": "- irate(node_network_transmit_bytes_total{job=\"10.178_mariadb_master_node_exporter_info\",device=~\"(?i)^(ens|eth).+$\"}[5m]) < 0",
     "legendFormat": "OUT ({{device}})"
    }
   ]
  },
  { "title": "MariaDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Top Command Counters",
   "type": "timeseries",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total{job=\"10.178_mariadb_master_info\"}[5s])>0) or irate(mysql_global_status_commands_total{job=\"10.178_mariadb_master_info\"}[5m])>0"
    }
   ]
  },
  {
   "title": "Rep_Master_Slave_Connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_slaves_connected{job=\"10.178_mariadb_master_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rep_Slave_running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_slave_running{job=\"10.183_mariadb_slave_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max(max_over_time(mysql_global_status_threads_connected{job=\"10.178_mariadb_master_info\"}[5s]) or mysql_global_status_threads_connected{job=\"10.178_mariadb_master_info\"})",
     "legendFormat": "Connections"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_max_used_connections{job=\"10.178_mariadb_master_info\"}",
     "legendFormat": "Max Used Connections"
    }
   ]
  },
  {
   "title": "MySQL Table Locks",
   "type": "bargauge",
   "description": "**Table Locks**\n\nMySQL takes a number of different locks for varying reasons. In this graph we see how many Table level locks MySQL has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_immediate{job=\"10.178_mariadb_master_info\"}[5s]) or irate(mysql_global_status_table_locks_immediate{job=\"10.178_mariadb_master_info\"}[5m])",
     "legendFormat": "Table Locks Immediate"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_waited{job=\"10.178_mariadb_master_info\"}[5s]) or irate(mysql_global_status_table_locks_waited{job=\"10.178_mariadb_master_info\"}[5m])",
     "legendFormat": "Table Locks Waited"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 20 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{job=\"10.178_mariadb_master_info\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mysql Read I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\", job=\"10.178_mariadb_master_info\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB_Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{job=\"10.178_mariadb_master_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "gauge",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{job=\"10.178_mariadb_master_info\"}",
     "legendFormat": "Max Used Connections"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{job=\"10.178_mariadb_master_info\"}[5s]) or irate(mysql_global_status_queries{job=\"10.178_mariadb_master_info\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Thread Cache",
   "type": "bargauge",
   "description": "**MySQL Thread Cache**\n\nThe thread_cache_size variable sets how many threads the server should cache to reuse. When a client disconnects, the client's threads are put in the cache if the cache is not full. It is autosized in MySQL 5.6.8 and above (capped to 100). Requests for threads are satisfied by reusing threads taken from the cache if possible, and only when the cache is empty is a new thread created.\n\n* *Threads_created*: The number of threads created to handle connections.\n* *Threads_cached*: The number of threads in the thread cache.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_thread_cache_size{job=\"10.178_mariadb_master_info\"}",
     "legendFormat": "Thread Cache Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_cached{job=\"10.178_mariadb_master_info\"}",
     "legendFormat": "Threads Cached"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_threads_created{job=\"10.178_mariadb_master_info\"}[5s]) or irate(mysql_global_status_threads_created{job=\"10.178_mariadb_master_info\"}[5m])",
     "legendFormat": "Threads Created"
    }
   ]
  },
  {
   "title": "Mysql Write I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 24 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=~\"insert|update|delete\", job=\"10.178_mariadb_master_info\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{job=\"10.178_mariadb_master_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Use",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mysql_global_status_innodb_buffer_pool_bytes_data{job=\"10.178_mariadb_master_info\"} / mysql_global_variables_innodb_buffer_pool_size{job=\"10.178_mariadb_master_info\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InnoDB_Lock",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_row_lock_waits{job=\"10.178_mariadb_master_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InnoDB_lock_time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_row_lock_time{job=\"10.178_mariadb_master_info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InnoDB Read I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_data_read{job=\"10.178_mariadb_master_info\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InnoDB Write I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_data_written{job=\"10.178_mariadb_master_info\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "M/W", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } }
 ]
}